name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build c++ program
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-ucrt-x86_64-gcc

      - name: Build
        shell: msys2 {0}
        run: |
          g++ -std=c++17 main.cpp -Iinclude -o weekly-random-recipe.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ''
          path: ./dist

      - name: Copy all files to dist
        run: |
          cp -r include dist/
          cp LICENSE README.md recipes.json.example dist/

      - name: Create ZIP Package
        run: |
          cd dist
          zip -r ../Weekly-Random-Recipe.zip .
          cd ..
          mv Weekly-Random-Recipe.zip Weekly-Random-Recipe-${{ github.ref_name }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Weekly-Random-Recipe-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}